FROM ahumeniy/flipkg-build-server-v2:latest 
ENV FZBRANCH=0.78.1

RUN git clone https://github.com/flipperdevices/flipperzero-firmware.git -b ${FZBRANCH} /App/flipper && \ 
    cd /App/flipper && \
    ./fbt
